### ISSUE TITLE
Normalizer problem with string

### ISSUE THREAD

**Issue by mehdibalouchi** [sobhe/hazm#142]
I have a problem using `Normalizer.normalize`. I copy & paste exact code in the Readme.md and it throws this error:
```
normalizer.normalize('اصلاح نويسه ها و استفاده از نیم‌فاصله پردازش را آسان مي كند')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mehdi/.local/lib/python2.7/site-packages/hazm/Normalizer.py", line 74, in normalize
    text = self.character_refinement(text)
  File "/home/mehdi/.local/lib/python2.7/site-packages/hazm/Normalizer.py", line 103, in character_refinement
    text = text.translate(self.translations)
TypeError: expected a string or other character buffer object
```

**Comment by nournia** [comment]
<div dir=rtl>

سلام
لطفا این خط رو هم از بالای فایل راهنما کپی کنید:
</div>

    from __future__ import unicode_literals
