### ISSUE TITLE
Error in instantiate `InformalNormalizer` class

### ISSUE THREAD

**Issue by ReS4** [sobhe/hazm#155]
سلام. موقع ساختن آبجکت از کلاس فوق، خطای زیر رخ می دهد که مربوط به عبارت با قاعده می باشد.
```
i_normalizer = InformalNormalizer()
```
```
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    i_normalizer = InformalNormalizer()
  File "C:\Anaconda2\lib\site-packages\hazm\InformalNormalizer.py", line 17, in __init__
    self.lemmatizer = Lemmatizer()
  File "C:\Anaconda2\lib\site-packages\hazm\Lemmatizer.py", line 32, in __init__
    tokenizer = WordTokenizer(words_file=default_words, verbs_file=verbs_file)
  File "C:\Anaconda2\lib\site-packages\hazm\WordTokenizer.py", line 53, in __init__
    "]", flags=re.UNICODE)
  File "C:\Anaconda2\lib\re.py", line 194, in compile
    return _compile(pattern, flags)
  File "C:\Anaconda2\lib\re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: bad character range
```

مفسر پایتون آخرین نسخه و از نوع anaconda می باشد.
```
import sys; print('Python %s on %s' % (sys.version, sys.platform))
Python 2.7.15 |Anaconda, Inc.| (default, Dec 10 2018, 21:57:18) [MSC v.1500 64 bit (AMD64)] on win32
```

**Comment by nournia** [comment]
<div dir=rtl>

سلام
عجیب هست.
ممکنه با پایتون معمولی تست کنید؟
