### ISSUE TITLE
NLTK was unable to find the java file!

### ISSUE THREAD

**Issue by mohagheghiyan** [sobhe/hazm#20]
با اجرای این کد به مشکل زیر برخوردم
اینترنت را زیر و رو کردم به جایی نرسیدم
از ویندوز 8 64 بیتی و پایتون 3.4 64 بیتی استفاده میکنم
لطفا یکی راهنمایی بفرماید

Traceback (most recent call last):
  File "<pyshell#17>", line 1, in <module>
    tagger.tag(word_tokenize('ما بسیار کتاب می‌خوانیم'))
  File "C:\Python34\lib\site-packages\nltk\tag\stanford.py", line 59, in tag
    return self.tag_sents([tokens])[0]
  File "C:\Python34\lib\site-packages\hazm\POSTagger.py", line 25, in tag_sents
    return super(stanford.POSTagger, self).tag_sents(refined)
  File "C:\Python34\lib\site-packages\nltk\tag\stanford.py", line 64, in tag_sents
    config_java(options=self.java_options, verbose=False)
  File "C:\Python34\lib\site-packages\nltk\internals.py", line 82, in config_java
    _java_bin = find_binary('java', bin, env_vars=['JAVAHOME', 'JAVA_HOME'], verbose=verbose, binary_names=['java.exe'])
  File "C:\Python34\lib\site-packages\nltk\internals.py", line 544, in find_binary
    binary_names, url, verbose))
  File "C:\Python34\lib\site-packages\nltk\internals.py", line 538, in find_binary_iter
    url, verbose):
  File "C:\Python34\lib\site-packages\nltk\internals.py", line 517, in find_file_iter
    raise LookupError('\n\n%s\n%s\n%s' % (div, msg, div))
LookupError: 

===========================================================================
NLTK was unable to find the java file!
Use software specific configuration paramaters or set the JAVAHOME environment variable.
===========================================================================

**Comment by nournia** [comment]
<div dir=rtl>

برای حل این مشکل باید:

بسته Java Runtime Environment مناسب سیستم‌تون رو نصب کنید، از [اینجا](http://filehippo.com/search?q=java) یا هر جای دیگه.

دستورات هضم رو اجرا کنید. اگر کار نکرد باید متغیر JAVAHOME رو در سیستم [تنظیم کنید](http://www.computerhope.com/issues/ch000549.htm). مثلا بذارید:
`C:\WINDOWS\system32\java.exe`
