### ISSUE TITLE
مشکل در خواندن فایل CSV

### ISSUE THREAD

**Issue by MrAliProgrammer** [sobhe/hazm#213]
با سلام و وقت بخیر
ببخشید بنده یک فایل csv که دارای اخبار فارسی بود را با استفاده را کتابخانه pandas خواندم ولی ارور زیر را نمایش داد
Traceback (most recent call last):
  File "C:\Users\vsl\Desktop\p1.py", line 25, in <module>
    df = pd.read_csv('1.csv')
  File "C:\Users\vsl\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\vsl\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "C:\Users\vsl\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "C:\Users\vsl\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas\_libs\parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas\_libs\parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas\_libs\parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas\_libs\parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas\_libs\parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in line 1081, saw 8

کتابخانه هضم هم وارد شده است. به نظر شما مشکل از چه چیزی می تواند باشد؟

**Comment by kokabi1365** [comment]
سلام.
این مشکل ارتباطی به کتابخانهٔ هضم ندارد. 
متن خطا را در اینترنت سرچ کنید.
https://stackoverflow.com/questions/18039057/python-pandas-error-tokenizing-data
