### ISSUE TITLE
مشکل parser

### ISSUE THREAD

**Issue by aminbag** [sobhe/hazm#56]
<pre>
from __future__ import unicode_literals
from hazm import *

tagger = POSTagger(model='resources/postagger.model')
lemmatizer = Lemmatizer()
parser = DependencyParser(tagger=tagger, lemmatizer=lemmatizer)
temp = 'زنگ‌ها برای که به صدا درمی‌آید؟'
parser.parse(word_tokenize(temp))
</pre>
   
سلام
من بعد از اجرای کد بالا که به صورت مستقیم در مثال ها آورده شده ، به ارور زیر بر میخورم:

<pre>
runfile('/home/aminbag/untitled1.py', wdir='/home/aminbag')
Traceback (most recent call last):

  File "<ipython-input-14-a806139048c4>", line 1, in <module>
    runfile('/home/aminbag/untitled1.py', wdir='/home/aminbag')

  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 78, in execfile
    builtins.execfile(filename, *where)

  File "/home/aminbag/untitled1.py", line 18, in <module>
    parser.parse(word_tokenize(temp))

  File "/usr/local/lib/python2.7/dist-packages/nltk-3.0.5-py2.7.egg/nltk/parse/api.py", line 45, in parse
    return next(self.parse_sents([sent], *args, **kwargs))

  File "/usr/local/lib/python2.7/dist-packages/hazm-0.5.2-py2.7.egg/hazm/DependencyParser.py", line 24, in parse_sents
    return self.parse_tagged_sents(tagged_sentences, verbose)

  File "/usr/local/lib/python2.7/dist-packages/hazm-0.5.2-py2.7.egg/hazm/DependencyParser.py", line 41, in parse_tagged_sents
    if self._execute(cmd, verbose) != 0:

  File "/usr/local/lib/python2.7/dist-packages/nltk-3.0.5-py2.7.egg/nltk/parse/malt.py", line 265, in _execute
    p = subprocess.Popen(cmd, stdout=output, stderr=output)

  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)

  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception

OSError: [Errno 2] No such file or directory

</pre>
  
بقیه توابع را آزمایش کردم و بدون مشکل کار میکنند . ولی در این تابع به این مشکل بر میخورم
در ضمن فولدر ریسورس ها نیز دقیقا کنار فایل پایتونم هست

**Comment by nournia** [comment]
<div dir=rtl>
ببینید java روی سیستم نصب هست؟

**Comment by aminbag** [comment]
بله . مشکل برطرف شد بعد از نصب جاوا .
با تشکر از زحمات شما
