### ISSUE TITLE
مشکل در POStagger

### ISSUE THREAD

**Issue by mitra8814** [sobhe/hazm#98]
سلام من قبلا با هضم کار کرده بودم و مشکلی نداشت الان که تقریبا بعد یک سال دوباره ازش استفاده کردم در قسمت 
POSTagger
با اررور زیر مواجه شدم:
TypeError: Can't instantiate abstract class POSTagger with abstract methods tag
ممنون می شوم راهنمایی بفرمایید خیلی بهش احتیاج دارم.

**Comment by mitra8814** [comment]
این اررور که در بیام قبل گفتم وقتی کد زیر را وارد می کنم رخ می دهد:
>>> from __future__ import unicode_literals
>>> from hazm import *
tagger = POSTagger(model='resources/postagger.model')
و بعد هم این ارور :
TypeError: Can't instantiate abstract class POSTagger with abstract methods tag

**Comment by mahboobnejati** [comment]
دقیقا برای نسخه ی 5 این مشکل را من هم دارم

**Comment by hatamiarash7** [comment]
من هم این مشکل رو برای کار با
django
دارم

**Comment by nournia** [comment]
<div dir=rtl>

سلام
نمی‌دونم دقیقا مشکل چی هست، ولی فکر کنم این دستور می‌تونه کمک بکنه:

    sudo pip install hazm --upgrade

چون ابزار هضم مدام تست می‌شه و این مشکل وجود نداره. مگر اینکه وابستگی‌ها در نسخه مناسب نصب نشده باشن.

**Comment by barooni69** [comment]
من هضم را توی ویندوز نصب کردم و نرمال سازی وتوکن بندی و عامیانه به رسمی رو انجام دادم الان نیاز به تحلیل صرفی دارم برای این کار یه فایلی که سایت بود را دانلود کردم و در پوشه کدم گذاشتم ولی بازم اررور میده

Traceback (most recent call last):
  File "C:/Users/PC Nima/Documents/pycharm_projct/preprocessor/POS/pos hazm.py", line 8, in <module>
    tagger = POSTagger(model='resources/postagger.model')
  File "C:\Python27\lib\site-packages\hazm-0.5.2-py2.7.egg\hazm\SequenceTagger.py", line 22, in __init__
    from wapiti import Model
ImportError: No module named wapiti

**Comment by nournia** [comment]
<div dir=rtl>

سلام
لطفا بخش نصب روی ویندوز رو در سایت نگاه کنید.

**Comment by zinasir** [comment]
سلام
 postagger خیلی کند اجرا میشه
در صورتی که ریشه یابی و غیره سرعت خوبی داره.
فولدر resorces رو داخل فولدر پروژم قرار دادم.
رو ابونتو با اسپایدر کار میکنم

**Comment by nournia** [comment]
<div dir=rtl>

سلام
با این خطایی که می‌ده عجیب هست که کار می‌کنه. البته در لینوکس هیچ مشکلی نیست و دیدن این خطا هم عجیبه.
ابزار برچسب‌زن صرفی بسیار سریع هست.
اگر مشکل حل شده لطفا اطلاع بدید.

**Comment by Saeedtrs** [comment]
با سلام 
منم در اوبونتو همین مشکل رو دارم 
  chunker = Chunker(model=resources/chunker.model)
TypeError: Can't instantiate abstract class Chunker with abstract methods tag

**Comment by nournia** [comment]
سلام
فکر می‌کنم این دستور مشکل رو حل می‌کنه:
  
     pip install https://github.com/sobhe/hazm/archive/master.zip --upgrade

**Comment by mehdi1602** [comment]
@zinasir 
سلام آیا تونستید این مشکل را رفع کنید؟

**Comment by elahesabetghadam** [comment]
this line of code:
       tagger = POSTagger(model='hazm/postagger.model')
return this error:
        error: cannot open input model file: hazm/postagger.model
	           <No such file or directory>
i think postagger.model really doesn't exists 
but i don't know the solution
i'm using version 7 of hazm

**Comment by elahesabetghadam** [comment]
i download the resources from the link that you put in the github
my problem is solved
Thanks

**Comment by fateme1373** [comment]
> i download the resources from the link that you put in the main page of hazm
> my problem is solved
> Thanks

can you mention to location where you put "resources" folder?

**Comment by AzitaAzimi** [comment]
after installing hazm with this command "pip install hazm", I have a problem. None of the resources in the hazm folder is working. I get this error "NameError: name 'POSTagger' is not defined". Even though, the package is in the same folder of the script.

**Comment by fotouhifar** [comment]
![image](https://user-images.githubusercontent.com/8702170/89610649-6cdc8a80-d8be-11ea-80e3-287e57857ea9.png)


---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-38-03163f59eea6> in <module>
----> 1 tagger = POSTagger(model='resources/postagger.model')

~\AppData\Roaming\Python\Python37\site-packages\hazm\SequenceTagger.py in __init__(self, patterns, **options)
     20 
     21         def __init__(self, patterns=[], **options):
---> 22                 from wapiti import Model
     23                 self.model = Model(patterns='\n'.join(patterns), **options)
     24 

ModuleNotFoundError: No module named 'wapiti'

**Comment by alimajnoon1377** [comment]
https://github.com/sobhe/hazm/issues/98#issuecomment-670322061
I have the same error

**Comment by jamal221** [comment]
If you installed conda, so in the conda  terminal write pip install hazm

**Comment by mostafa18181** [comment]
سلام بر دوستان
postagger.model
رو از کجا باید بگیرم؟؟
